# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
permalink: /posts/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title: Hoyang's Memo
description: A front-end developer who is looking forward to embrace web potentials.
url: https://hoyangtsai.github.io
baseurl:
urlimg: https://hoyangtsai.github.io/images
markdown: kramdown

excerpt_separator: '<!-- more -->'
default_bg: /assets/sitebg.jpg
default_logo: /assets/sitelogo.png
safe: false
timezone: Asia/Taipei
future: true

## code highlight options
highlighter: rouge
syntax_highlighter: rouge
input: GFM

gems:
  - jekyll-paginate
  - jemoji
  - kramdown
  - rouge

paginate: 5
paginate_path: /posts/page:num/

ampdir: /amp

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "test", "package.json", "node_modules", "LICENSE", "_plugins", "public/dormant"]

# About/contact
author:
  name: Ho-Yang Tsai
  url:  https://hoyangtsai.github.io/
  avatar: /IMG_0942.jpg
  email:  hoyang.t@gmail.com

# Owner/author information
owner:
  name: Ho-Yang Tsai
  avatar: /IMG_0942.jpg
  email: hoyang.t@gmail.com
  description:
  twitter: hoyangtsai
  # facebook: hoyangtsai
  github: hoyangtsai
  linkedin: https://www.linkedin.com/in/hoyangtsai
  instagram:
  flickr:

## sidebar links:
# For external links add external: true
links:
  - title: <i class="fas fa-home"></i>&nbsp;&nbsp;Home
    url: /
  - title: <i class="fas fa-user"></i>&nbsp;&nbsp;About
    url: /about/
  - title: <i class="far fa-pencil"></i>&nbsp;&nbsp;Posts
    url: /posts/
  - title: <i class="far fa-tags"></i>&nbsp;&nbsp;Tags
    url: /tags/
  - title: <i class="fas fa-archive"></i>&nbsp;&nbsp;Archive
    url: /archive/
  - title: <i class="fas fa-address-book"></i>&nbsp;&nbsp;Contact
    url: /contact/
  - title: <i class="fas fa-rss"></i>&nbsp;&nbsp;Feed
    url: /feed.xml

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
#twitter_widget_id: xyz123abc

# Add disqus username for Disqus comment board:
disqus_shortname: hoyangtsai

facebook:
  app_id: 1069355273095594

google:
  analytics: UA-36297587-6
  site_verification: AA9TuZRgJxTNDH0EwMVgqegbQqZjvO1m8xSVVyRg1ls

collections:
  amp:
    output: true
    permalink: /:collection/posts/:year/:month/:day/:title/

sass:
  sass_dir: _sass
  style: compressed
