# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
permalink: /:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title: Hoyang's Memo
description: A front-end developer who is looking forward to embrace web potentials.
url: https://hoyangtsai.github.io
baseurl:
urlimg: https://hoyangtsai.github.io/images/
markdown: kramdown

excerpt_separator: '<!-- more -->'
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
timezone: Asia/Taipei
future: true

## code highlight options
highlighter: rouge
syntax_highlighter: rouge
input: GFM

gems:
  - jekyll-paginate
  - jemoji
  - font-awesome-sass
  - kramdown
  - rouge
  - amp-jekyll

paginate: 5
paginate_path: /blog/page:num/

ampdir: /amp

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name: Ho-Yang Tsai
  url:  https://hoyangtsai.github.io/
  avatar: IMG_0942.jpg
  email:  hoyang.t@gmail.com

# Owner/author information
owner:
  name: Ho-Yang Tsai
  avatar: IMG_0942.jpg
  email: hoyang.t@gmail.com
  description:
  twitter: hoyangtsai
  # facebook: hoyangtsai
  github: hoyangtsai
  linkedin: https://www.linkedin.com/in/hoyangtsai
  instagram:
  flickr:

## sidebar links:
# For external links add external: true
links:
  - title: <i class="fa fa-home"></i> Home
    url: /
  - title: <i class="fa fa-user"></i> About
    url: /about/
  - title: <i class="fa fa-pencil"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
  - title: <i class="fa fa-address-book"></i> Contact
    url: /contact/
  - title: <i class="fa fa-rss"></i> Feed
    url: /feed.xml

# Google Custom Search:
#google_search: xyz123abc

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
#twitter_widget_id: xyz123abc

# Add disqus username for Disqus comment board:
disqus_shortname: hoyangtsai

# Analytics and webmaster tools stuff goes here
google_analytics: UA-36297587-6

# Add facebook application appId
facebook_appId: 1069355273095594

google_verify: AA9TuZRgJxTNDH0EwMVgqegbQqZjvO1m8xSVVyRg1ls
